# Stage de runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000

# Stage de SDK para build + watch
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copia só o csproj primeiro para cache de restore
COPY *.csproj ./
RUN dotnet restore

# Copia o restante do código
COPY . ./

# Comando padrão de desenvolvimento
CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]
