// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace reagen_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119201703_NamedOptionsTPT")]
    partial class NamedOptionsTPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NamedOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NamedOptions");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Brand", b =>
                {
                    b.HasBaseType("NamedOption");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("ControlAgency", b =>
                {
                    b.HasBaseType("NamedOption");

                    b.ToTable("ControlAgencies", (string)null);
                });

            modelBuilder.Entity("Laboratory", b =>
                {
                    b.HasBaseType("NamedOption");

                    b.ToTable("Laboratories", (string)null);
                });

            modelBuilder.Entity("Supplier", b =>
                {
                    b.HasBaseType("NamedOption");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Brand", b =>
                {
                    b.HasOne("NamedOption", null)
                        .WithOne()
                        .HasForeignKey("Brand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControlAgency", b =>
                {
                    b.HasOne("NamedOption", null)
                        .WithOne()
                        .HasForeignKey("ControlAgency", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Laboratory", b =>
                {
                    b.HasOne("NamedOption", null)
                        .WithOne()
                        .HasForeignKey("Laboratory", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Supplier", b =>
                {
                    b.HasOne("NamedOption", null)
                        .WithOne()
                        .HasForeignKey("Supplier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
