// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace reagen_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119213428_AjustAlreadyExisting")]
    partial class AjustAlreadyExisting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NamedOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NamedOptions");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Purity")
                        .HasColumnType("double precision");

                    b.Property<int>("ReagentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ReagentId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("Reagent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ControlAgencyId")
                        .HasColumnType("integer");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ControlAgencyId");

                    b.ToTable("Reagent");
                });

            modelBuilder.Entity("Vial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LaboratoryId");

                    b.HasIndex("PackageId");

                    b.ToTable("Vial");
                });

            modelBuilder.Entity("Brand", b =>
                {
                    b.HasBaseType("NamedOption");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("ControlAgency", b =>
                {
                    b.HasBaseType("NamedOption");

                    b.ToTable("ControlAgencies", (string)null);
                });

            modelBuilder.Entity("Laboratory", b =>
                {
                    b.HasBaseType("NamedOption");

                    b.ToTable("Laboratories", (string)null);
                });

            modelBuilder.Entity("Supplier", b =>
                {
                    b.HasBaseType("NamedOption");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("Package", b =>
                {
                    b.HasOne("Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Reagent", "Reagent")
                        .WithMany()
                        .HasForeignKey("ReagentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Measure.Size", "Size", b1 =>
                        {
                            b1.Property<int>("PackageId")
                                .HasColumnType("integer");

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer");

                            b1.HasKey("PackageId");

                            b1.ToTable("Package");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.Navigation("Brand");

                    b.Navigation("Reagent");

                    b.Navigation("Size")
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Reagent", b =>
                {
                    b.HasOne("ControlAgency", "ControlAgency")
                        .WithMany()
                        .HasForeignKey("ControlAgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("Measure.Size", "Sizes", b1 =>
                        {
                            b1.Property<int>("ReagentId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer");

                            b1.HasKey("ReagentId", "Id");

                            b1.ToTable("Reagent_Sizes");

                            b1.WithOwner()
                                .HasForeignKey("ReagentId");
                        });

                    b.Navigation("ControlAgency");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("Vial", b =>
                {
                    b.HasOne("Laboratory", "Laboratory")
                        .WithMany()
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laboratory");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Brand", b =>
                {
                    b.HasOne("NamedOption", null)
                        .WithOne()
                        .HasForeignKey("Brand", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControlAgency", b =>
                {
                    b.HasOne("NamedOption", null)
                        .WithOne()
                        .HasForeignKey("ControlAgency", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Laboratory", b =>
                {
                    b.HasOne("NamedOption", null)
                        .WithOne()
                        .HasForeignKey("Laboratory", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Supplier", b =>
                {
                    b.HasOne("NamedOption", null)
                        .WithOne()
                        .HasForeignKey("Supplier", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
