// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReagenBack.Core.Contexts;

#nullable disable

namespace ReagenBack.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219031154_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ReagenBack.Core.Models.ControlAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ControlAgencies", (string)null);
                });

            modelBuilder.Entity("ReagenBack.Core.Models.FundingSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FundingSources", (string)null);
                });

            modelBuilder.Entity("ReagenBack.Core.Models.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Laboratories", (string)null);
                });

            modelBuilder.Entity("ReagenBack.Core.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FundingSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Purity")
                        .HasColumnType("REAL");

                    b.Property<int>("ReagentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FundingSourceId");

                    b.HasIndex("ReagentId");

                    b.HasIndex("SizeId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Packages", (string)null);
                });

            modelBuilder.Entity("ReagenBack.Core.Models.Reagent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControlAgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dimension")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ControlAgencyId");

                    b.ToTable("Reagents", (string)null);
                });

            modelBuilder.Entity("ReagenBack.Core.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("ReagentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReagentId");

                    b.ToTable("Sizes", (string)null);
                });

            modelBuilder.Entity("ReagenBack.Core.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("ReagenBack.Core.Models.Vial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OutDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LaboratoryId");

                    b.HasIndex("PackageId");

                    b.ToTable("Vials", (string)null);
                });

            modelBuilder.Entity("ReagenBack.Core.Models.Package", b =>
                {
                    b.HasOne("ReagenBack.Core.Models.FundingSource", "FundingSource")
                        .WithMany()
                        .HasForeignKey("FundingSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReagenBack.Core.Models.Reagent", "Reagent")
                        .WithMany()
                        .HasForeignKey("ReagentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReagenBack.Core.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReagenBack.Core.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FundingSource");

                    b.Navigation("Reagent");

                    b.Navigation("Size");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ReagenBack.Core.Models.Reagent", b =>
                {
                    b.HasOne("ReagenBack.Core.Models.ControlAgency", "ControlAgency")
                        .WithMany()
                        .HasForeignKey("ControlAgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ControlAgency");
                });

            modelBuilder.Entity("ReagenBack.Core.Models.Size", b =>
                {
                    b.HasOne("ReagenBack.Core.Models.Reagent", "Reagent")
                        .WithMany()
                        .HasForeignKey("ReagentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reagent");
                });

            modelBuilder.Entity("ReagenBack.Core.Models.Vial", b =>
                {
                    b.HasOne("ReagenBack.Core.Models.Laboratory", "Laboratory")
                        .WithMany()
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ReagenBack.Core.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Laboratory");

                    b.Navigation("Package");
                });
#pragma warning restore 612, 618
        }
    }
}
